name: Build macos dmg
on:
  workflow_dispatch:
jobs:
  build:
    name: macos-arm
    runs-on: macos-14
    permissions:
      contents: write
      packages: write
    steps:
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install -g asar webpack webpack-cli
          npm install webpack --save-dev
      - name: Install dependencies
        run: yarn install

      - name: Build ${{ runner.arch }}
        run: yarn make
      - name: Show Directory
        run: |
          pwd
          ls -la
